/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeLamaRouteImport } from './routes/home-lama'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as DashboardUndanganRouteImport } from './routes/dashboard.undangan'
import { Route as DashboardTemplateRouteImport } from './routes/dashboard.template'
import { Route as DashboardTamuRouteImport } from './routes/dashboard.tamu'
import { Route as DashboardRsvpRouteImport } from './routes/dashboard.rsvp'
import { Route as DashboardPengaturanRouteImport } from './routes/dashboard.pengaturan'
import { Route as DashboardBuatRouteImport } from './routes/dashboard.buat'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as AdminVoucherRouteImport } from './routes/admin.voucher'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMediaRouteImport } from './routes/admin.media'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLamaRoute = HomeLamaRouteImport.update({
  id: '/home-lama',
  path: '/home-lama',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUndanganRoute = DashboardUndanganRouteImport.update({
  id: '/undangan',
  path: '/undangan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplateRoute = DashboardTemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTamuRoute = DashboardTamuRouteImport.update({
  id: '/tamu',
  path: '/tamu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRsvpRoute = DashboardRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPengaturanRoute = DashboardPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuatRoute = DashboardBuatRouteImport.update({
  id: '/buat',
  path: '/buat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminVoucherRoute = AdminVoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/home-lama': typeof HomeLamaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voucher': typeof AdminVoucherRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/buat': typeof DashboardBuatRoute
  '/dashboard/pengaturan': typeof DashboardPengaturanRoute
  '/dashboard/rsvp': typeof DashboardRsvpRoute
  '/dashboard/tamu': typeof DashboardTamuRoute
  '/dashboard/template': typeof DashboardTemplateRoute
  '/dashboard/undangan': typeof DashboardUndanganRoute
  '/u/$slug': typeof USlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home-lama': typeof HomeLamaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voucher': typeof AdminVoucherRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/buat': typeof DashboardBuatRoute
  '/dashboard/pengaturan': typeof DashboardPengaturanRoute
  '/dashboard/rsvp': typeof DashboardRsvpRoute
  '/dashboard/tamu': typeof DashboardTamuRoute
  '/dashboard/template': typeof DashboardTemplateRoute
  '/dashboard/undangan': typeof DashboardUndanganRoute
  '/u/$slug': typeof USlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/home-lama': typeof HomeLamaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voucher': typeof AdminVoucherRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/buat': typeof DashboardBuatRoute
  '/dashboard/pengaturan': typeof DashboardPengaturanRoute
  '/dashboard/rsvp': typeof DashboardRsvpRoute
  '/dashboard/tamu': typeof DashboardTamuRoute
  '/dashboard/template': typeof DashboardTemplateRoute
  '/dashboard/undangan': typeof DashboardUndanganRoute
  '/u/$slug': typeof USlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/home-lama'
    | '/login'
    | '/register'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/voucher'
    | '/dashboard/billing'
    | '/dashboard/buat'
    | '/dashboard/pengaturan'
    | '/dashboard/rsvp'
    | '/dashboard/tamu'
    | '/dashboard/template'
    | '/dashboard/undangan'
    | '/u/$slug'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home-lama'
    | '/login'
    | '/register'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/voucher'
    | '/dashboard/billing'
    | '/dashboard/buat'
    | '/dashboard/pengaturan'
    | '/dashboard/rsvp'
    | '/dashboard/tamu'
    | '/dashboard/template'
    | '/dashboard/undangan'
    | '/u/$slug'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/home-lama'
    | '/login'
    | '/register'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/voucher'
    | '/dashboard/billing'
    | '/dashboard/buat'
    | '/dashboard/pengaturan'
    | '/dashboard/rsvp'
    | '/dashboard/tamu'
    | '/dashboard/template'
    | '/dashboard/undangan'
    | '/u/$slug'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  HomeLamaRoute: typeof HomeLamaRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  USlugRoute: typeof USlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-lama': {
      id: '/home-lama'
      path: '/home-lama'
      fullPath: '/home-lama'
      preLoaderRoute: typeof HomeLamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/undangan': {
      id: '/dashboard/undangan'
      path: '/undangan'
      fullPath: '/dashboard/undangan'
      preLoaderRoute: typeof DashboardUndanganRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/template': {
      id: '/dashboard/template'
      path: '/template'
      fullPath: '/dashboard/template'
      preLoaderRoute: typeof DashboardTemplateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tamu': {
      id: '/dashboard/tamu'
      path: '/tamu'
      fullPath: '/dashboard/tamu'
      preLoaderRoute: typeof DashboardTamuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rsvp': {
      id: '/dashboard/rsvp'
      path: '/rsvp'
      fullPath: '/dashboard/rsvp'
      preLoaderRoute: typeof DashboardRsvpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pengaturan': {
      id: '/dashboard/pengaturan'
      path: '/pengaturan'
      fullPath: '/dashboard/pengaturan'
      preLoaderRoute: typeof DashboardPengaturanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/buat': {
      id: '/dashboard/buat'
      path: '/buat'
      fullPath: '/dashboard/buat'
      preLoaderRoute: typeof DashboardBuatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/voucher': {
      id: '/admin/voucher'
      path: '/voucher'
      fullPath: '/admin/voucher'
      preLoaderRoute: typeof AdminVoucherRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVoucherRoute: typeof AdminVoucherRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMediaRoute: AdminMediaRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVoucherRoute: AdminVoucherRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBuatRoute: typeof DashboardBuatRoute
  DashboardPengaturanRoute: typeof DashboardPengaturanRoute
  DashboardRsvpRoute: typeof DashboardRsvpRoute
  DashboardTamuRoute: typeof DashboardTamuRoute
  DashboardTemplateRoute: typeof DashboardTemplateRoute
  DashboardUndanganRoute: typeof DashboardUndanganRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBuatRoute: DashboardBuatRoute,
  DashboardPengaturanRoute: DashboardPengaturanRoute,
  DashboardRsvpRoute: DashboardRsvpRoute,
  DashboardTamuRoute: DashboardTamuRoute,
  DashboardTemplateRoute: DashboardTemplateRoute,
  DashboardUndanganRoute: DashboardUndanganRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  HomeLamaRoute: HomeLamaRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  USlugRoute: USlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
